use new v1 interface

diff --git a/assets/get b/assets/get
--- a/assets/get
+++ b/assets/get
@@ -1,38 +1,23 @@
 #!/bin/sh
 # vim: set ft=sh
 
-set -e
-
-exec 3>&1 # make stdout available as fd 3 for the result
-exec 1>&2 # redirect all output to stderr for logging
+set -e -u
 
 source $(dirname $0)/common.sh
-
-destination=$1
-
-if [ -z "$destination" ]; then
-  echo "usage: $0 <path/to/destination>" >&2
-  exit 1
-fi
 
 # for jq
 PATH=/usr/local/bin:$PATH
 
-payload=$(mktemp $TMPDIR/git-resource-request.XXXXXX)
+load_pubkey $REQUEST
 
-cat > $payload <&0
-
-load_pubkey $payload
-
-uri=$(jq -r '.source.uri // ""' < $payload)
-branch=$(jq -r '.source.branch // ""' < $payload)
-ref=$(jq -r '.version.ref // "HEAD"' < $payload)
-fetch=$(jq -r '(.params.fetch // [])[]' < $payload)
-submodules=$(jq -r '(.params.submodules // "all")' < $payload)
+uri=$(jq -r '.source.uri // ""' < $REQUEST)
+branch=$(jq -r '.source.branch // ""' < $REQUEST)
+ref=$(jq -r '.version.ref // "HEAD"' < $REQUEST)
+fetch=$(jq -r '(.params.fetch // [])[]' < $REQUEST)
+submodules=$(jq -r '(.params.submodules // "all")' < $REQUEST)
 
 if [ -z "$uri" ]; then
-  echo "invalid payload (missing uri):" >&2
-  cat $payload >&2
+  echo "invalid source configuration; missing uri" >&2
   exit 1
 fi
 
@@ -41,9 +26,9 @@ if [ -n "$branch" ]; then
   branchflag="--branch $branch"
 fi
 
-git clone $uri $branchflag $destination
+git clone $uri $branchflag $DESTINATION
 
-cd $destination
+cd $DESTINATION
 
 git checkout -q $ref
 git log -1 --oneline
@@ -66,4 +51,4 @@ done
 jq -n "{
   version: {ref: $(git rev-parse HEAD | jq -R .)},
   metadata: $(git_metadata)
-}" >&3
+}" > $RESPONSE
diff --git a/assets/put b/assets/put
--- a/assets/put
+++ b/assets/put
@@ -1,52 +1,38 @@
 #!/bin/sh
 # vim: set ft=sh
 
-set -e
-
-exec 3>&1 # make stdout available as fd 3 for the result
-exec 1>&2 # redirect all output to stderr for logging
+set -e -u
 
 source $(dirname $0)/common.sh
-
-source=$1
-
-if [ -z "$source" ]; then
-  echo "usage: $0 <path/to/source>"
-  exit 1
-fi
 
 # for jq
 PATH=/usr/local/bin:$PATH
 
-payload=$(mktemp $TMPDIR/git-resource-request.XXXXXX)
+load_pubkey $REQUEST
 
-cat > $payload <&0
-
-load_pubkey $payload
-
-uri=$(jq -r '.source.uri // ""' < $payload)
-branch=$(jq -r '.source.branch // ""' < $payload)
-repository=$(jq -r '.params.repository // ""' < $payload)
-tag=$(jq -r '.params.tag // ""' < $payload)
-tag_prefix=$(jq -r '.params.tag_prefix // ""' < $payload)
-rebase=$(jq -r '.params.rebase // false' < $payload)
+uri=$(jq -r '.source.uri // ""' < $REQUEST)
+branch=$(jq -r '.source.branch // ""' < $REQUEST)
+repository=$(jq -r '.params.repository // ""' < $REQUEST)
+tag=$(jq -r '.params.tag // ""' < $REQUEST)
+tag_prefix=$(jq -r '.params.tag_prefix // ""' < $REQUEST)
+rebase=$(jq -r '.params.rebase // false' < $REQUEST)
 
 if [ -z "$uri" ]; then
-  echo "invalid payload (missing uri)"
+  echo "invalid source configuration (missing uri)"
   exit 1
 fi
 
 if [ -z "$branch" ]; then
-  echo "invalid payload (missing branch)"
+  echo "invalid source configuration (missing branch)"
   exit 1
 fi
 
 if [ -z "$repository" ]; then
-  echo "invalid payload (missing repository)"
+  echo "invalid source configuration (missing repository)"
   exit 1
 fi
 
-cd $source
+cd $SOURCE
 
 if [ -n "$tag" ] && [ ! -f "$tag" ]; then
   echo "tag file '$tag' does not exist"
@@ -115,4 +101,4 @@ fi
 jq -n "{
   version: {ref: $(git rev-parse HEAD | jq -R .)},
   metadata: $(git_metadata)
-}" >&3
+}" > $RESPONSE
